### ISSUE TITLE
bug(python 3): FileNotFoundError: [Errno 2] No such file or directory: 'python'

### ISSUE THREAD

**Issue by Kristinita** [Kristinita/SashaMiscellaneous#15]
### 1. Summary

I can't import module from [**sorcery**](https://github.com/alexmojaki/sorcery) package in Repl.it.

In local machine I successful use sorcery.

### 2. Configuration

+ [**Example program**](https://repl.it/@Kristinita/SashaSO-SorcerySwitch),
+ [**Minimal code**](https://repl.it/@Kristinita/SashaBug-SorceryImport):

+ `main.py`

```python
from sorcery import switch
```

### 3. Steps to reproduce

I press to `Run`.

### 4. Expected behavior

No traceback.

### 5. Actual behavior

```python
Traceback (most recent call last):
  File "python", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1006, in _handle_fromlist
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

Thanks.

**Comment by Kristinita** [comment]
[**Temporary solution of Tim Chen**](https://repl.it/bugs/p/bugpython-3-filenotfounderror-errno-2-no-such-file-or-directory-python)
